#! /bin/bash

# used for generating MSE and PSNR calculating result

./PSNRCalculation 01_8bit.bmp 01_8bit_Biateral_3.bmp
./PSNRCalculation 01_8bit.bmp 01_8bit_Biateral_5.bmp
./PSNRCalculation 01_8bit.bmp 01_8bit_Biateral_9.bmp
./PSNRCalculation 01_8bit.bmp 01_8bit_Gaussian_3.bmp
./PSNRCalculation 01_8bit.bmp 01_8bit_Gaussian_5.bmp
./PSNRCalculation 01_8bit.bmp 01_8bit_Gaussian_9.bmp
./PSNRCalculation 01_8bit.bmp 01_8bit_mean_3.bmp
./PSNRCalculation 01_8bit.bmp 01_8bit_mean_5.bmp
./PSNRCalculation 01_8bit.bmp 01_8bit_mean_9.bmp
./PSNRCalculation 01_8bit.bmp 01_8bit_median_3.bmp
./PSNRCalculation 01_8bit.bmp 01_8bit_median_5.bmp
./PSNRCalculation 01_8bit.bmp 01_8bit_median_9.bmp
./PSNRCalculation 01_8bit.bmp 01_8bit_1_default.bmp
./PSNRCalculation 01_8bit.bmp 01_8bit_1_001.bmp
./PSNRCalculation 01_8bit.bmp 01_8bit_1_005.bmp
./PSNRCalculation 01_8bit.bmp 01_8bit_1_01.bmp
./PSNRCalculation 01_8bit.bmp 01_8bit_1_05.bmp
./PSNRCalculation 01_8bit.bmp 01_8bit_1_1.bmp
./PSNRCalculation 01_8bit.bmp 01_8bit_1_2.bmp
./PSNRCalculation 01_8bit.bmp 01_8bit_1_5.bmp
./PSNRCalculation 01_8bit.bmp 01_8bit_2_default.bmp
./PSNRCalculation 01_8bit.bmp 01_8bit_2_001.bmp
./PSNRCalculation 01_8bit.bmp 01_8bit_2_005.bmp
./PSNRCalculation 01_8bit.bmp 01_8bit_2_01.bmp
./PSNRCalculation 01_8bit.bmp 01_8bit_2_05.bmp
./PSNRCalculation 01_8bit.bmp 01_8bit_2_1.bmp
./PSNRCalculation 01_8bit.bmp 01_8bit_2_2.bmp
./PSNRCalculation 01_8bit.bmp 01_8bit_2_5.bmp

./PSNRCalculation 2_8bit.bmp 2_8bit_Biateral_3.bmp
./PSNRCalculation 2_8bit.bmp 2_8bit_Biateral_5.bmp
./PSNRCalculation 2_8bit.bmp 2_8bit_Biateral_9.bmp
./PSNRCalculation 2_8bit.bmp 2_8bit_Gaussian_3.bmp
./PSNRCalculation 2_8bit.bmp 2_8bit_Gaussian_5.bmp
./PSNRCalculation 2_8bit.bmp 2_8bit_Gaussian_9.bmp
./PSNRCalculation 2_8bit.bmp 2_8bit_mean_3.bmp
./PSNRCalculation 2_8bit.bmp 2_8bit_mean_5.bmp
./PSNRCalculation 2_8bit.bmp 2_8bit_mean_9.bmp
./PSNRCalculation 2_8bit.bmp 2_8bit_median_3.bmp
./PSNRCalculation 2_8bit.bmp 2_8bit_median_5.bmp
./PSNRCalculation 2_8bit.bmp 2_8bit_median_9.bmp
./PSNRCalculation 2_8bit.bmp 2_8bit_1_default.bmp
./PSNRCalculation 2_8bit.bmp 2_8bit_1_001.bmp
./PSNRCalculation 2_8bit.bmp 2_8bit_1_005.bmp
./PSNRCalculation 2_8bit.bmp 2_8bit_1_01.bmp
./PSNRCalculation 2_8bit.bmp 2_8bit_1_05.bmp
./PSNRCalculation 2_8bit.bmp 2_8bit_1_1.bmp
./PSNRCalculation 2_8bit.bmp 2_8bit_1_2.bmp
./PSNRCalculation 2_8bit.bmp 2_8bit_1_5.bmp
./PSNRCalculation 2_8bit.bmp 2_8bit_2_default.bmp
./PSNRCalculation 2_8bit.bmp 2_8bit_2_001.bmp
./PSNRCalculation 2_8bit.bmp 2_8bit_2_005.bmp
./PSNRCalculation 2_8bit.bmp 2_8bit_2_01.bmp
./PSNRCalculation 2_8bit.bmp 2_8bit_2_05.bmp
./PSNRCalculation 2_8bit.bmp 2_8bit_2_1.bmp
./PSNRCalculation 2_8bit.bmp 2_8bit_2_2.bmp
./PSNRCalculation 2_8bit.bmp 2_8bit_2_5.bmp

./PSNRCalculation cameraman.bmp cameraman_Biateral_3.bmp
./PSNRCalculation cameraman.bmp cameraman_Biateral_5.bmp
./PSNRCalculation cameraman.bmp cameraman_Biateral_9.bmp
./PSNRCalculation cameraman.bmp cameraman_Gaussian_3.bmp
./PSNRCalculation cameraman.bmp cameraman_Gaussian_5.bmp
./PSNRCalculation cameraman.bmp cameraman_Gaussian_9.bmp
./PSNRCalculation cameraman.bmp cameraman_mean_3.bmp
./PSNRCalculation cameraman.bmp cameraman_mean_5.bmp
./PSNRCalculation cameraman.bmp cameraman_mean_9.bmp
./PSNRCalculation cameraman.bmp cameraman_median_3.bmp
./PSNRCalculation cameraman.bmp cameraman_median_5.bmp
./PSNRCalculation cameraman.bmp cameraman_median_9.bmp
./PSNRCalculation cameraman.bmp cameraman_1_default.bmp
./PSNRCalculation cameraman.bmp cameraman_1_001.bmp
./PSNRCalculation cameraman.bmp cameraman_1_005.bmp
./PSNRCalculation cameraman.bmp cameraman_1_01.bmp
./PSNRCalculation cameraman.bmp cameraman_1_05.bmp
./PSNRCalculation cameraman.bmp cameraman_1_1.bmp
./PSNRCalculation cameraman.bmp cameraman_1_2.bmp
./PSNRCalculation cameraman.bmp cameraman_1_5.bmp
./PSNRCalculation cameraman.bmp cameraman_2_default.bmp
./PSNRCalculation cameraman.bmp cameraman_2_001.bmp
./PSNRCalculation cameraman.bmp cameraman_2_005.bmp
./PSNRCalculation cameraman.bmp cameraman_2_01.bmp
./PSNRCalculation cameraman.bmp cameraman_2_05.bmp
./PSNRCalculation cameraman.bmp cameraman_2_1.bmp
./PSNRCalculation cameraman.bmp cameraman_2_2.bmp
./PSNRCalculation cameraman.bmp cameraman_2_5.bmp

./PSNRCalculation house.bmp house_Biateral_3.bmp
./PSNRCalculation house.bmp house_Biateral_5.bmp
./PSNRCalculation house.bmp house_Biateral_9.bmp
./PSNRCalculation house.bmp house_Gaussian_3.bmp
./PSNRCalculation house.bmp house_Gaussian_5.bmp
./PSNRCalculation house.bmp house_Gaussian_9.bmp
./PSNRCalculation house.bmp house_mean_3.bmp
./PSNRCalculation house.bmp house_mean_5.bmp
./PSNRCalculation house.bmp house_mean_9.bmp
./PSNRCalculation house.bmp house_median_3.bmp
./PSNRCalculation house.bmp house_median_5.bmp
./PSNRCalculation house.bmp house_median_9.bmp
./PSNRCalculation house.bmp house_1_default.bmp
./PSNRCalculation house.bmp house_1_001.bmp
./PSNRCalculation house.bmp house_1_005.bmp
./PSNRCalculation house.bmp house_1_01.bmp
./PSNRCalculation house.bmp house_1_05.bmp
./PSNRCalculation house.bmp house_1_1.bmp
./PSNRCalculation house.bmp house_1_2.bmp
./PSNRCalculation house.bmp house_1_5.bmp
./PSNRCalculation house.bmp house_2_default.bmp
./PSNRCalculation house.bmp house_2_001.bmp
./PSNRCalculation house.bmp house_2_005.bmp
./PSNRCalculation house.bmp house_2_01.bmp
./PSNRCalculation house.bmp house_2_05.bmp
./PSNRCalculation house.bmp house_2_1.bmp
./PSNRCalculation house.bmp house_2_2.bmp
./PSNRCalculation house.bmp house_2_5.bmp

./PSNRCalculation jetplane.bmp jetplane_Biateral_3.bmp
./PSNRCalculation jetplane.bmp jetplane_Biateral_5.bmp
./PSNRCalculation jetplane.bmp jetplane_Biateral_9.bmp
./PSNRCalculation jetplane.bmp jetplane_Gaussian_3.bmp
./PSNRCalculation jetplane.bmp jetplane_Gaussian_5.bmp
./PSNRCalculation jetplane.bmp jetplane_Gaussian_9.bmp
./PSNRCalculation jetplane.bmp jetplane_mean_3.bmp
./PSNRCalculation jetplane.bmp jetplane_mean_5.bmp
./PSNRCalculation jetplane.bmp jetplane_mean_9.bmp
./PSNRCalculation jetplane.bmp jetplane_median_3.bmp
./PSNRCalculation jetplane.bmp jetplane_median_5.bmp
./PSNRCalculation jetplane.bmp jetplane_median_9.bmp
./PSNRCalculation jetplane.bmp jetplane_1_default.bmp
./PSNRCalculation jetplane.bmp jetplane_1_001.bmp
./PSNRCalculation jetplane.bmp jetplane_1_005.bmp
./PSNRCalculation jetplane.bmp jetplane_1_01.bmp
./PSNRCalculation jetplane.bmp jetplane_1_05.bmp
./PSNRCalculation jetplane.bmp jetplane_1_1.bmp
./PSNRCalculation jetplane.bmp jetplane_1_2.bmp
./PSNRCalculation jetplane.bmp jetplane_1_5.bmp
./PSNRCalculation jetplane.bmp jetplane_2_default.bmp
./PSNRCalculation jetplane.bmp jetplane_2_001.bmp
./PSNRCalculation jetplane.bmp jetplane_2_005.bmp
./PSNRCalculation jetplane.bmp jetplane_2_01.bmp
./PSNRCalculation jetplane.bmp jetplane_2_05.bmp
./PSNRCalculation jetplane.bmp jetplane_2_1.bmp
./PSNRCalculation jetplane.bmp jetplane_2_2.bmp
./PSNRCalculation jetplane.bmp jetplane_2_5.bmp



